name: Loki sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/logging-sync-main-flow.yaml'
    - '.github/workflows/merge-loki.yaml'
  push:
    paths:
    - '.github/workflows/logging-sync-main-flow.yaml'
    - '.github/workflows/merge-loki.yaml'
jobs:
  loki-sync:
    uses: ./.github/workflows/logging-sync-main-flow.yaml
    with:
      upstream: grafana/loki
      downstream: openshift/loki
      sandbox: rhobs/loki
      commit-filter: '(operator):'
      restore-upstream: >-
        CHANGELOG.md
        VERSION
        go.mod
        go.sum
      restore-downstream: >-
        OWNERS
        Dockerfile.ocp
        Dockerfile.promtail.ocp
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.LOGGING_SLACK_WEBHOOK_URL }}
