name: ACM Memcached exporter merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' #@weekly
  pull_request:
    paths:
    - '.github/workflows/merge-acm-flow.yaml'
    - '.github/workflows/merge-acm-memcached-exporter.yaml'
  push:
    paths:
    - '.github/workflows/merge-acm-flow.yaml'
    - '.github/workflows/merge-acm-memcached-exporter.yaml'
jobs:
  memcached-exporter-merge:
    uses: ./.github/workflows/merge-acm-flow.yaml
    with:
      upstream: prometheus/memcached_exporter
      downstream: stolostron/memcached_exporter
      sandbox: rhobs/acm-memcached_exporter
      go-version: "1.24"
      restore-downstream: >-
         OWNERS
      restore-upstream: >-
         CHANGELOG.md
         VERSION
         go.mod
         go.sum
         pkg
         cmd
    secrets:
      pr-app-id: ${{ secrets.ACM_APP_ID }}
      pr-app-private-key: ${{ secrets.ACM_APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.ACM_CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.ACM_CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.ACM_SLACK_WEBHOOK_URL }}