name: resource-state-metrics merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
  pull_request:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-resource-state-metrics.yaml'
  push:
    paths:
    - '.github/workflows/merge-flow.yaml'
    - '.github/workflows/merge-resource-state-metrics.yaml'

jobs:
  resource-state-metrics-merge:
    uses: ./.github/workflows/merge-flow.yaml
    with:
      upstream: kubernetes-sigs/resource-state-metrics
      downstream: openshift/kubernetes-sigs-resource-state-metrics
      sandbox: rhobs/kubernetes-sigs-resource-state-metrics
      restore-downstream: OWNERS
      restore-upstream: >-
        .github/
        CONTRIBUTING.md
        Dockerfile
        README.md
        VERSION
        go.mod
        go.sum
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
