name: Thanos merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
jobs:
  thanos-merge:
    uses: rhobs/syncbot/.github/workflows/merge-flow.yaml@main
    with:
      upstream: thanos-io/thanos
      downstream: openshift/thanos
      sandbox: rhobs/thanos
      go-version: 1.17
      restore-upstream: tutorials CHANGELOG.md VERSION
    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
